defaults:
  - launcher: local
  - _self_

world:
  env_name: swm/OGBScene-v0
  num_envs: ${eval.num_eval}
  max_episode_steps: ??? # set to >= eval_budget in run()
  env_type: single
  ob_type: states
  multiview: False
  width: 224
  height: 224
  visualize_info: False
  terminate_at_goal: True

dataset:
  keys_to_cache:
    - action

seed: 42
policy: random  # path to HJEPA checkpoint

l2_solver:
  _target_: stable_worldmodel.solver.CEMSolver
  model: ???
  batch_size: 1
  num_samples: 300
  var_scale: 1.0
  n_steps: 10
  topk: 30
  device: cuda
  seed: ${seed}

l1_solver:
  _target_: stable_worldmodel.solver.CEMSolver
  model: ???
  batch_size: 1
  num_samples: 300
  var_scale: 1.0
  n_steps: 30
  topk: 30
  device: cuda
  seed: ${seed}

l2_plan_config:
  horizon: 3
  receding_horizon: 1
  action_block: 1
  history_len: 1
  warm_start: false

l1_plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 5
  history_len: 1
  warm_start: true

eval:
  num_eval: 50
  goal_offset_steps: 75
  eval_budget: 150
  img_size: 224
  dataset_name: ogbench/scene_single_expert
  callables:
    - method: set_state
      args:
        qpos:
          value: qpos
        qvel:
          value: qvel
        button_state_0:
          value: privileged_button_0_state
        button_state_1:
          value: privileged_button_1_state
    - method: set_cube_target_pos
      args:
        cube_id:
          value: 0
          in_dataset: False
        target_pos:
          value: goal_privileged_block_0_pos
        target_quat:
          value: goal_privileged_block_0_quat
    - method: set_target_button_state
      args:
        button_id:
          value: 0
          in_dataset: False
        target_state:
          value: goal_privileged_button_0_state
    - method: set_target_button_state
      args:
        button_id:
          value: 1
          in_dataset: False
        target_state:
          value: goal_privileged_button_1_state
    - method: set_target_drawer_pos
      args:
        target_pos:
          value: goal_privileged_drawer_pos
    - method: set_target_window_pos
      args:
        target_pos:
          value: goal_privileged_window_pos

output:
  filename: hogb_scene_results.txt
